spring.application.name=library
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET}
jwt.access-token.expiration-ms=${JWT_ACCESS_EXPIRATION:900000}
jwt.refresh-token.expiration-ms=${JWT_REFRESH_EXPIRATION:604800}

clickhouse.url=${CLICKHOUSE_URL}
clickhouse.user=${CLICKHOUSE_USER}
clickhouse.password=${CLICKHOUSE_PASS}
